# render.yaml - VERIFIED LATEST VERSION
services:
  - name: amu-survey-web
    type: web
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --no-input"
    startCommand: "python manage.py migrate && gunicorn amusurvey.wsgi:application --log-file -"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: amusurvey-db # This refers to the database you created manually on Render
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 1
      - key: DJANGO_SETTINGS_MODULE
        value: amusurvey.settings
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "amu-survey-web.onrender.com"
    numInstances: 1
    plan: starter
    healthCheckPath: /health