services:
  - name: amusurvey-db # Name of the database service
    type: psql # Corrected type for a PostgreSQL database
    databaseName: amusurvey_db_prod
    user: amusurvey_user
    plan: free
  - name: amu-survey-web # Name of the web service
    type: web # Corrected type for a web service
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn amusurvey.wsgi:application --log-file -"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: amusurvey-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DJANGO_SETTINGS_MODULE
        value: amusurvey.settings
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "amu-survey-web.onrender.com"
    numInstances: 1
    plan: starter
    healthCheckPath: /health
  - name: migrate-amu-survey-db # Name of the job service
    type: job # Corrected type for a job service
    env: python
    buildCommand: "./build.sh"
    startCommand: "python manage.py migrate"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: amusurvey-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
    autoDeploy: true