services:
  - name: amusurvey-db
    type: database # This is correct for defining a database resource
    databaseName: amusurvey_db_prod
    user: amusurvey_user
    plan: free # Ensure this plan is available and valid
    # You might need to specify the database engine, e.g., engine: pg or engine: postgres
    # Based on Render's docs, for type: database, the 'engine' key is often required or assumed.
    # Let's add it to be explicit.
    engine: postgres # Explicitly defining the database engine

  - name: amu-survey-web
    type: web
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn amusurvey.wsgi:application --log-file -"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: amusurvey-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DJANGO_SETTINGS_MODULE
        value: amusurvey.settings
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "amu-survey-web.onrender.com"
    numInstances: 1
    plan: starter
    healthCheckPath: /health

  - name: migrate-amu-survey-db
    type: job
    env: python
    buildCommand: "./build.sh"
    startCommand: "python manage.py migrate"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: amusurvey-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
    autoDeploy: true