# Generated by Django 5.2.4 on 2025-07-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='The date and time when the survey closes.', null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='The date and time when the survey becomes active.', null=True),
        ),
    ]
