# Generated by Django 5.2.4 on 2025-07-06 13:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_survey_end_date_survey_start_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['survey', 'order']},
        ),
        migrations.AlterModelOptions(
            name='survey',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='survey',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='status',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='survey',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck this to close the survey to new responses.'),
        ),
        migrations.AddField(
            model_name='survey',
            name='target_audience',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('FACULTY', 'Faculty'), ('STAFF', 'Staff'), ('OTHER', 'Other Community Member'), ('ALL', 'All Respondents')], default='ALL', help_text='Choose who is eligible to take this survey.', max_length=20),
        ),
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Determines the order in which questions appear.'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('TEXT', 'Text (Short Answer)'), ('TEXTAREA', 'Paragraph (Long Answer)'), ('CHOICE', 'Multiple Choice (Single Answer)'), ('MULTICHOICE', 'Checkboxes (Multiple Answers)'), ('RATING', 'Rating (1-5)')], default='TEXT', help_text='Choose the type of answer you expect.', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='survey',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='survey',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_surveys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='survey',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='survey',
            name='title',
            field=models.CharField(help_text='The title of the survey.', max_length=200),
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to=settings.AUTH_USER_MODEL)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='surveys.survey')),
            ],
            options={
                'unique_together': {('survey', 'respondent')},
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, null=True)),
                ('choices', models.ManyToManyField(blank=True, related_name='answers', to='surveys.choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.question')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.response')),
            ],
        ),
    ]
