# Generated by Django 5.2.4 on 2025-07-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_alter_survey_description_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='Optional: The survey will close on this date/time.', null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='Optional: The survey will become available on this date/time.', null=True),
        ),
    ]
