# Generated by Django 5.2.4 on 2025-07-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_survey_end_date_survey_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('FACULITY', 'Faculity'), ('STAFF', 'Staff'), ('SURVEY_CREATOR', 'Survey Creator'), ('OTHER', 'Other Community Member')], help_text="Select the user's role in the community.", max_length=20),
        ),
        migrations.AlterField(
            model_name='survey',
            name='target_audience',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('FACULITY', 'Faculity'), ('STAFF', 'Staff'), ('SURVEY_CREATOR', 'Survey Creator'), ('OTHER', 'Other Community Member'), ('ALL', 'All Respondents')], default='ALL', help_text='Choose who is eligible to take this survey.', max_length=20),
        ),
    ]
