# Generated by Django 5.2.4 on 2025-07-25 12:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_alter_profile_user_type_alter_survey_target_audience'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Enable this to make the survey accessible via the public shareable link.'),
        ),
        migrations.AddField(
            model_name='survey',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique public identifier for the shareable link.'),
        ),
    ]
