# Generated by Django 5.2.4 on 2025-07-25 12:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0007_survey_is_public_survey_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique public identifier for the shareable link.', unique=True),
        ),
    ]
